name: Publish to Pub.dev

# 流程触发时机，create当有标签创建时触发，如 v1.0.0。当然也可以选择别的触发时机，如 push，release 等
on: push

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      # 拉去仓库代码
      - name: "Checkout"
        uses: actions/checkout@master
      # 发布插件
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@master
        with:
          # 设置发布插件需要的 Token
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}